### PR TITLE
Fixes #23; Adds 'stockfish' command line switch

### LINKED ISSUE #23: Support for Custom Stockfish Binary Path
Hi there! This tool seems to be useful but the problem is it may not work in Apple M1 chips as it is using lichess's fork of Stockfish. Can you add an option to set a custom path for Stockfish-binary in CLI arguments?

### PR DESCRIPTION
**Pull request by karol-brejna-i**
Add 'stockfish' command line switch; move helper functions to utils package

### CODE REVIEW

**Comment by karol-brejna-i** [comment]
Waits for MacBook testing.

**Comment by karol-brejna-i** [comment]
`build-stockfish.sh` modified so it now works on MacBook M1, too.
`--stockfish` command line switch added for supplying custom Stockfish path.
Tested on Linux (x86-64) and macOS (M1).
Ready to merge.

**Review by vitogit — APPROVED** [review]
Excellent

**Comment by vitogit** [comment]
This PR is good so is merged.
Something I would like in the future is to remove references to  `modules.fishnet.fishnet import stockfish_command` because is using the fishnet fork of stockfish I think we should use the official but as far as I know it has no binaries, so not sure what's the best way to do it.

**Comment by karol-brejna-i** [comment]
Yes, I attempted to switch to official-stockfish, but found no binaries. Let's monitor if it changes and then let's get back to the topic.

**Pull request merged**
