### PR TITLE
Add LICENSE (Apache 2.0) file

### PR DESCRIPTION
**Pull request by karol-brejna-i**
Solving #7

### CODE REVIEW

**Review by vitogit — CHANGES_REQUESTED** [review]
Can you update the PR to be a MIT license? Also remove the .DS_Store and .gitignore

**Comment by karol-brejna-i** [comment]
License change to MIT.

**Comment by karol-brejna-i** [comment]
Can you suggest a way (dedicated PR) to update .gitignore and remove non-project files (.DS_Store)?

**Review by vitogit — APPROVED** [review]

**Comment by vitogit** [comment]
@karol-brejna-i I think the current .gitignore is good (It ignores the DS_Store files), if you want, can you crate a new PR removing the DS_Store file, the opening_counter.py file (it was a personal project and is not related with this), also the `puzzles.service` file seems that is not used.

**Pull request merged**
